DELETE TOP (100) PERCENT FROM PROJETO.AJUDA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.ASSISTENTE WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.CHECK_DENTISTA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.CLINICA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.CONSULTA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.DENTISTA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.FORNECEDOR WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.MATERIAL_DENTARIO WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.MEDICAMENTO WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.PACIENTE WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.PAGA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.PESSOA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.PRESCRICAO WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.RECECIONISTA WHERE 1=1
DELETE TOP (100) PERCENT FROM PROJETO.STAFF WHERE 1=1


